In [1]:
import numpy as np

In [2]:
dir(np) #All functions of numpy

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [3]:
np.sqrt(100)

10.0

In [4]:
np.ceil(25.2)

26.0

In [5]:
np.floor(25.2)

25.0

In [6]:
l = [17,25,80,15]

np.amin(l) #minimum

15

In [7]:
np.amax(l) #maximum

80

In [8]:
n = np.array(l)
n 

array([17, 25, 80, 15])

In [9]:
type(n) #Numpy Array

numpy.ndarray

In [12]:
n.dtype #Integer array datatype

dtype('int32')

In [13]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2D array or Matrix
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#Dtype conversion

a = np.array([1,2,3],dtype=float)
a

array([1., 2., 3.])

In [16]:
# Copy array

b = np.asarray(a)
b

array([1., 2., 3.])

In [17]:
# Matrix

my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print("Type/class of this object : ",type(mat))
print("Here is the marks \n------\n",mat,"\n-----------")
print("print dimension of this matrix : ",mat.ndim)#ndim gives dimension,2 for a matrix and 1 for vector
print("size of the matrix : ",mat.size)#size shows total number elements
print("Shape of the matrix : ",mat.shape)#shape shows how many rows and column
print("Data Type of the matrix ; ",mat.dtype)

Type/class of this object :  <class 'numpy.ndarray'>
Here is the marks 
------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----------
print dimension of this matrix :  2
size of the matrix :  9
Shape of the matrix :  (3, 3)
Data Type of the matrix ;  int32


In [19]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a = np.arange(10,50,5) # Start,stop,step
a

array([10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
#Reverse:

b = np.arange(50,10,-5)
b

array([50, 45, 40, 35, 30, 25, 20, 15])

In [24]:
np.linspace(10,40,5) #Linear spacing 5 numbers(equal intervals) within 10 and 40

array([10. , 17.5, 25. , 32.5, 40. ])

In [26]:
np.linspace(2.0,10.0,num=4,endpoint=True,retstep=True)

(array([ 2.        ,  4.66666667,  7.33333333, 10.        ]),
 2.6666666666666665)

In [27]:
np.linspace(10,20,retstep=True)

(array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
        11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
        12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
        13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
        14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
        15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
        16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
        17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
        18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
        19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ]),
 0.20408163265306123)

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros([5,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.ones([4,3])*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [35]:
x = np.arange(30).reshape(5,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [40]:
np.random.seed(5) #Each seed will generate similar data
np.random.rand(3,3) #3x3 unifrom distribution

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ]])

In [42]:
print("Number from normal distribution with zero mean and standard deviation 1 i.e standard noraml")
print(np.random.randn(3,3))

Number from normal distribution with zero mean and standard deviation 1 i.e standard noraml
[[-0.20786334 -1.35218081 -1.02077299]
 [ 1.2334356   0.65340573 -0.21706802]
 [-0.11069605  0.5439582  -0.29673933]]


In [43]:
print("Random integer vector : ",np.random.randint(5,20,10))

Random integer vector :  [ 5 18 14  6 14  5 13 12 12 14]


In [45]:
def generate_otp():
    otp=np.random.randint(1000,10000,1)
    print("Your Otp is ",otp)
    user_otp=int(input("Enter Your OTP Here: "))
    if otp==user_otp:
        print("Log in Sucessfully")
    else:
        print("Your OTP is invalid")
generate_otp()

Your Otp is  [8919]
Enter Your OTP Here: 8919
Log in Sucessfully
